version: "3.9"  # optional since v1.27.0
services:
  server:
     image: generic-ntier/tomcat-staticonly
     build:
       context: .
       dockerfile: Dockerfile_tomcat_staticonly
     ports:
     - "8888:8080"
#     environment:
#     - CATALINA_BASE=/usr/local/tomcat
#     - CATALINA_HOME=/usr/local/tomcat
#     - CATALINA_TMPDIR=/usr/local/tomcat/temp
#     - JRE_HOME=/usr/bin/java
#     - CLASSPATH="/usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar"
